"""esquema_dos_fases_y_tarifas

Revision ID: d383e5fb03b6
Revises: 
Create Date: 2026-09-07 00:51:08.555415

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd383e5fb03b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacios', sa.Column('tarifa_hora', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('reservas', sa.Column('monto_total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('reservas', sa.Column('expira_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'expira_en')
    op.drop_column('reservas', 'monto_total')
    op.drop_column('espacios', 'tarifa_hora')
    # ### end Alembic commands ###
